### ISSUE TITLE
實作「tag3」欄位（難易度)

### ISSUE THREAD

**Issue by bobchao** [COSCUP/2019#10]
目前網站上沒有顯示「難易度」（tag3）欄位，再請放上

難易度是一個只有四種狀態的屬性

1. (empty)  - 可以不顯示或留白
2. beginner | 入門
3. skilled | 中階
4. advanced | 進階

**Comment by bingluen** [comment]
Implement on c89c25a1cfb2cd58d066bac5dc4231af1708187c
