### ISSUE TITLE
顯示時間差了八個小時

### ISSUE THREAD

**Issue by bobchao** [COSCUP/2019#11]
## Steps

1. Go to http://staging-2019.coscup.org/programs/
2. Check the first cell of the programme

## Expect

The first cell, 入場時間, should be displayed as "08:30 ~ 09:00"

## Actual Result

It shows "00:30 ~ 01:00"

## Note

![IMAGE 2019-06-05 00:01:35](https://user-images.githubusercontent.com/168931/58894712-16594680-8725-11e9-89d4-70985b1b7f83.jpg)

**Comment by bingluen** [comment]
Fix on https://github.com/COSCUP/2019/commit/f4f768c0c9965d6457c741211a8a546133764b07

**Comment by bobchao** [comment]
confirm fixed
