### ISSUE TITLE
行動版頁面在首次讀入時無法切換日期

### ISSUE THREAD

**Issue by bobchao** [COSCUP/2019#12]
## Steps

1. 進入 http://staging-2019.coscup.org/programs/
2. 點擊 Day 2
3. 再點擊 Day 1
4. 使用瀏覽器的 Reload，等待頁面重新載入
5. 點擊 Day 2
6. 再點擊 Day 1

## Expect

3-4 跟 5-6 的行為一致，都在點擊 Day 2 時切換到 Day 2 的議程表、點擊 Day 1 時切換到 Day 1 的議程表

## Actual Result

3-4 將無法切換日期，但 5-6 可以

![2019-06-06_13-56-40 (1)](https://user-images.githubusercontent.com/168931/59010284-59b9cf00-8863-11e9-81d8-2a367e543631.gif)

## Note

懷疑可能跟 #9 相關

**Comment by bingluen** [comment]
我嘗試用了以下方式(電腦部分是搭配響應設計模式)，重現不出問題QQ
- MacOS + Chrome
- MacOS + FireFox
- MacOS + Safari
- Windows 10 + Chrome 
- Windows 10 + Firefox
- iPhone 5 (iOS 10.3.3)
- iPhone 6S (iOS  12.3.1)
- iPhone Max (iOS 12.3.1)
- iPad Air (iOS 12.1)

我嘗試調整實作方式，看看有沒有好一點
https://github.com/COSCUP/2019/commit/b9706dc88207a3421f46080e0b3ab1c26dbed3b9

**Comment by bobchao** [comment]
Hummm 我現在用手機也無法重現了，怪…

這兩天手上沒電腦，如果都無法重現就先關了這張吧，感恩
