### ISSUE TITLE
議程總表上的「難易度」會與題目造成混淆

### ISSUE THREAD

**Issue by bobchao** [COSCUP/2019#19]
見圖，建議調整 style 或者總表上隱藏難易度、到行動版面或單一議題內容再顯示
![2019-06-20_17-50-39](https://user-images.githubusercontent.com/168931/59839916-0166ef00-9384-11e9-8887-6100b849037e.png)

**Comment by othree** [comment]
單色

<img width="1525" alt="螢幕快照 2019-06-20 下午11 29 13" src="https://user-images.githubusercontent.com/16474/59861354-40f8ff80-93b3-11e9-87a6-95414033e473.png">

**Comment by othree** [comment]
三色（顏色目前沒很仔細挑的）

<img width="1525" alt="螢幕快照 2019-06-20 下午11 32 20" src="https://user-images.githubusercontent.com/16474/59861579-b4027600-93b3-11e9-8f7b-3424bb5cea32.png">

**Comment by othree** [comment]
補個中文的，看看要單色還是三色版喔

<img width="1525" alt="螢幕快照 2019-06-20 下午11 34 10" src="https://user-images.githubusercontent.com/16474/59861712-f035d680-93b3-11e9-84cd-9974e8eeaca6.png">

**Comment by bobchao** [comment]
可否考慮試試以三色版的 beginner 的顏色為 skilled, 明度降低一些為 advanced, 明度提高為 beginner？

**Comment by othree** [comment]
<img width="1525" alt="螢幕快照 2019-06-21 上午11 27 54" src="https://user-images.githubusercontent.com/16474/59895575-a4b51400-9417-11e9-8a5d-3eef677541b6.png">

**Comment by bobchao** [comment]
這個我  ok, 感恩

**Comment by tigercosmos** [comment]
有顏色感覺很不錯呢！
