### ISSUE TITLE
議程表沒顯示講者名字

### ISSUE THREAD

**Issue by pingooo** [COSCUP/2019#23]
如圖，每個時段顯示的資訊包括講題、地點、長度、語言、難易度，可是沒有講者。

![4688056456839168](https://user-images.githubusercontent.com/127246/60028621-a4ae5180-966d-11e9-8cac-c20567db669e.png)

講者是聽眾決定要不要聽的重要依據之一，可否把講者姓名加上去？

**Comment by bingluen** [comment]
@bobchao  Can you share your opinions about this issue ?

**Comment by bobchao** [comment]
@bingluen  I tried to add a few tweaks for this, please review #25.

**Comment by bobchao** [comment]
![2019-07-01_15-10-01](https://user-images.githubusercontent.com/168931/60417553-49eb9b80-9c13-11e9-86fa-95babe101e93.png)
![2019-07-01_15-09-54](https://user-images.githubusercontent.com/168931/60417557-4ce68c00-9c13-11e9-87c2-8d073288b7c2.png)
![2019-07-01_15-09-34](https://user-images.githubusercontent.com/168931/60417563-4eb04f80-9c13-11e9-964d-357070274b6a.png)
![2019-07-01_15-09-31](https://user-images.githubusercontent.com/168931/60417567-507a1300-9c13-11e9-9f4c-e1988226d525.png)

**Comment by bobchao** [comment]
fixed in #25
