### ISSUE TITLE
议程表字体设置不支持简体中文

### ISSUE THREAD

**Issue by greyli** [COSCUP/2019#24]
COSCUP.org 的字体设置不支持简体中文，见下图。建议更新字体设置，或是把这部分简体中文议题信息（包括标题、简介、讲者姓名和个人简介）转换成繁体中文。如果需要更新议题信息，我可以进行协助。

![image](https://user-images.githubusercontent.com/12967000/60232276-b478a080-98ce-11e9-8cd4-7eecf5e7a396.png)

**Comment by greyli** [comment]
从字体设置来看，首位字体是「思源黑体繁中」，部分不支持的简中字符会 fallback 到第二位的「微软正黑体」。如果把第二位换成「微软雅黑」，不仔细看的话看不到区别：

![image](https://user-images.githubusercontent.com/12967000/60318915-54096200-99a7-11e9-84ac-9b871fbecc91.png)

**Comment by bingluen** [comment]
Using `Noto Sans SC` as fallback at 4ded3a6da096c0619abbcd937c27498fbb45439f

**Comment by greyli** [comment]
This issue appeared again, it may related with https://github.com/COSCUP/2019/commit/bd20962ff3ad7648b9cbb3d127d97a43021e412f.
