### ISSUE TITLE
議程表第一欄在 1000px-1279px 時會被遮住

### ISSUE THREAD

**Issue by bobchao** [COSCUP/2019#7]
## Steps

1. Open a browser window with 1280px width
2. Go to http://staging-2019.coscup.org/en/programs/
3. Resize the browser window to around 1000px width

## Expect

The first column, Main Track, is always visible in its full width.

## Result

![2019-06-05_00-15-50 (1)](https://user-images.githubusercontent.com/168931/58895761-4bff2f00-8727-11e9-86d9-b11bf66f5456.gif)

**Comment by bobchao** [comment]
現況沒有要解，暫時 workaround: 1279 以下全進 mobile 版面。

**Comment by bingluen** [comment]
> 現況沒有要解，暫時 workaround: 1279 以下全進 mobile 版面。

Workaround has been implemented on 4f4fd8266eeb94af74c3a17ab01d18f0c29ddcca
