### ISSUE TITLE
切換 Day 1 / Day 2 時，有機會資料重疊

### ISSUE THREAD

**Issue by bobchao** [COSCUP/2019#9]
還沒有找出 100% re-produce steps，但都出現在將 Day 1 切換到 Day 2、或 Day 2 切換到 Day 1 的時候。假設是 1 -> 2，那點擊並出現這樣的問題以後，Day 2 將無法再度點擊，反之亦然。

（我猜是某個 state toggle 有啥問題）
![IMAGE 2019-06-05 12:57:25](https://user-images.githubusercontent.com/168931/58931228-77b6ff00-8791-11e9-9cf3-3ab8dd9e8905.jpg)

**Comment by bobchao** [comment]
記下 #12 再度測試後，目前發現「首次讀入頁面時」會造成版面重疊，但 reload 後就不會了。

Tested on Chrome & Firefox on Mac

**Comment by bobchao** [comment]
Coin 這個應該修好了，等 review / merge

https://github.com/COSCUP/2019/pull/14

**Comment by bingluen** [comment]
> Coin 這個應該修好了，等 review / merge
> 
> #14

Merged~
